version: "3.3"
services:
  blog-ui:
    image: registry.cn-hangzhou.aliyuncs.com/douyacun/blog-ui:latest
    container_name: blog-ui
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://blog-ui:ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    environments:
      HOST: htts://www.douyacun.com
      GITHUB_CLIENT_ID: 25fc4f51f48cb5d52edf
    ports:
      - 3000:3000
