version: "3.3"
services:
  ui:
    image: registry.cn-hangzhou.aliyuncs.com/douyacun/tea-ui:latest
    container_name: ui
    environment:
      NODE_ENV: production
      CDN_HOST: https://cdn.douyacun.com
    volumes:
      - "/data/web/ui/node_modules:/app/node_modules"
    ports:
      - 3000:3000
