version: "3.3"
services:
  ui:
    image: registry.cn-hangzhou.aliyuncs.com/douyacun/tea-ui:latest
    container_name: ui
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://blog-ui:ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      HOST: htts://www.douyacun.com
      GITHUB_CLIENT_ID: https://github.com/login/oauth/authorize?client_id=25fc4f51f48cb5d52edf&scope=user:email
    ports:
      - 3000:3000
