version: "3.3"
services:
  ui:
    image: registry.cn-hangzhou.aliyuncs.com/douyacun/tea-ui:latest
    container_name: ui
    environment:
      HOSTNAME: www.douyacun.com
      HOST: https://www.douyacun.com
      PROTOCOL: https
      NODE_ENV: production
      CDN_HOST: http://cdn.douyacun.com
    ports:
      - 3000:3000
